# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communism', '0001_initial'),
        ('conduit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedbox',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conduit.DynamicPicker'),
        ),
        migrations.AddField(
            model_name='namedbox',
            name='slice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communism.Slice'),
        ),
        migrations.AddField(
            model_name='namedbox',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communism.NamedBoxTemplate'),
        ),
        migrations.AddField(
            model_name='javascript',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communism.Theme'),
        ),
        migrations.AddField(
            model_name='commune',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communism.Theme'),
        ),
        migrations.CreateModel(
            name='MagicSection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('communism.section',),
        ),
        migrations.AlterUniqueTogether(
            name='slice',
            unique_together=set([('commune', 'display_order')]),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('element_id', 'element_type'), ('realm', 'extends', 'display_order'), ('realm', 'keyname')]),
        ),
        migrations.AlterUniqueTogether(
            name='namedbox',
            unique_together=set([('slice', 'gridx', 'gridy', 'display_order'), ('slice', 'keyname')]),
        ),
    ]
